export const ownerDemo = {
  email: "demo@localbuzz.app",
  password: "demo123",
};

export const influencerDemo = {
  email: "influencer@localbuzz.app",
  password: "demo123",
};

export const demoBusiness = {
  id: "biz_demo_1",
  business_name: "GreenLeaf Wellness Studio",
  business_type: "Health & Wellness",
  location: "Berkeley, CA",
  neighborhood: "North Berkeley",
  phone: "(510) 555-0182",
  language: "English",
  customer_emails: Array.from({ length: 47 }, (_, i) => `customer${i + 1}@example.com`),
  customer_phones: Array.from({ length: 32 }, (_, i) => `+15105550${String(i + 100).slice(-3)}`),
};

/** Curated for Health & Wellness / spa / yoga demos (Berkeley–Oakland). */
export const wellnessDemoEvents = [
  {
    id: "wellness_evt_1",
    name: "Berkeley Community Yoga & Mindfulness Morning",
    date: "Saturday May 3 · 8:00 AM",
    location: "North Berkeley Park",
    attendance: 180,
    distance: 1.5,
    niches: ["Wellness", "Yoga", "Mindfulness", "Community"],
    score: "96% match for wellness studios",
    description: "Outdoor flows, breathwork intro, and local holistic vendors — ideal for cross-promoting class passes.",
  },
  {
    id: "wellness_evt_2",
    name: "East Bay Holistic Health Fair",
    date: "Sunday May 11 · 10:00 AM",
    location: "Oakland Marriott City Center",
    attendance: 650,
    distance: 4,
    niches: ["Wellness", "Nutrition", "Fitness", "Spa"],
    score: "94% match for health & wellness",
    description: "Vendor booths, mini treatments, and speaker sessions on sleep and stress — great for sampling services.",
  },
  {
    id: "wellness_evt_3",
    name: "Women’s Wellness Brunch & Panel",
    date: "Saturday May 17 · 11:30 AM",
    location: "Temescal, Oakland",
    attendance: 120,
    distance: 2.8,
    niches: ["Wellness", "Community", "Self-care"],
    score: "91% match for boutique wellness",
    description: "Intimate brunch with panel on sustainable self-care — strong alignment for member referrals.",
  },
  {
    id: "wellness_evt_4",
    name: "Bay Trail Sunset Meditation Walk",
    date: "Friday May 23 · 6:30 PM",
    location: "Berkeley Marina",
    attendance: 90,
    distance: 3.2,
    niches: ["Meditation", "Wellness", "Outdoor"],
    score: "89% match for mindfulness-focused brands",
    description: "Guided walking meditation along the bay — perfect co-host for breathwork or recovery workshops.",
  },
];

export const events = [
  {
    id: "event_1",
    name: "Oakland Bridal Expo",
    date: "Saturday April 26",
    location: "Oakland Convention Center",
    attendance: 500,
    distance: 1.2,
    niches: ["Beauty", "Nails", "Spa", "Fashion"],
    score: "94% relevant for nail salons",
    description: "Bridal vendors and beauty-focused visitors looking for wedding-ready services.",
  },
  {
    id: "event_2",
    name: "San Jose Night Food Festival",
    date: "Friday April 25",
    location: "Downtown San Jose",
    attendance: 2000,
    distance: 8,
    niches: ["Restaurant", "Food Truck", "Bakery", "Coffee"],
    score: "88% relevant for food businesses",
    description: "Large nighttime event featuring local food vendors and family entertainment.",
  },
  {
    id: "event_3",
    name: "Bay Area Small Business Week",
    date: "April 28 - May 2",
    location: "Various Oakland locations",
    attendance: 1200,
    distance: 3,
    niches: ["All businesses"],
    score: "90% relevant for local SMBs",
    description: "Community-wide programs for awareness, offers, and neighborhood business growth.",
  },
  {
    id: "event_4",
    name: "Fruitvale Cultural Festival",
    date: "Friday April 25",
    location: "Fruitvale Village Oakland",
    attendance: 800,
    distance: 2.1,
    niches: ["Restaurant", "Retail", "Food Truck"],
    score: "86% relevant for neighborhood brands",
    description: "High-footfall cultural festival with music, food, and family-friendly programming.",
  },
  {
    id: "event_5",
    name: "Silicon Valley Night Market",
    date: "Saturday April 26",
    location: "San Jose",
    attendance: 1500,
    distance: 9,
    niches: ["Food", "Retail", "Beauty", "Lifestyle"],
    score: "89% relevant for lifestyle brands",
    description: "Trendy evening market with younger audiences and high social media engagement.",
  },
];

export const influencers = [
  {
    id: "creator_1",
    name: "Sofia Martinez",
    handle: "@sofia.oakland.beauty",
    location: "Oakland",
    followers: 8200,
    engagement: 4.2,
    niches: ["Beauty", "Nails"],
    budget: "$50-100",
    match: 96,
  },
  {
    id: "creator_2",
    name: "Jenny Tran",
    handle: "@jennytran.bayareaeats",
    location: "San Jose",
    followers: 5600,
    engagement: 6.1,
    niches: ["Food", "Lifestyle"],
    budget: "$30-80",
    match: 88,
  },
  {
    id: "creator_3",
    name: "Marcus Lee",
    handle: "@marcus.bayarealife",
    location: "San Francisco",
    followers: 12000,
    engagement: 3.8,
    niches: ["Lifestyle", "Local"],
    budget: "$100-150",
    match: 79,
  },
  {
    id: "creator_4",
    name: "Priya Sharma",
    handle: "@priya.nailart.sf",
    location: "San Francisco",
    followers: 3400,
    engagement: 7.2,
    niches: ["Beauty", "Nails"],
    budget: "$25-50",
    match: 94,
  },
  {
    id: "creator_5",
    name: "Carlos Rivera",
    handle: "@carlos.oakland.eats",
    location: "Oakland",
    followers: 6800,
    engagement: 5.1,
    niches: ["Food", "Local"],
    budget: "$40-90",
    match: 85,
  },
  {
    id: "creator_6",
    name: "Anh Nguyen",
    handle: "@anh.bayarea.beauty",
    location: "San Jose",
    followers: 4200,
    engagement: 6.8,
    niches: ["Beauty", "Lifestyle"],
    budget: "$20-60",
    match: 91,
  },
];
